# Generated by Django 6.1.1 on 2026-10-06 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_masterprofile_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки мастера')),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientprofile', verbose_name='Профиль клиента (если зарегистрирован в системе)')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_customers', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers_customer',
                'unique_together': {('master', 'phone')},
            },
        ),
    ]
