[project]
name = "profiflow"
version = "0.17.0-dev"
description = "Сервис онлайн-записи для бьюти-мастеров и студий"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-tailwind>=4.5.0",
    "gunicorn>=26.2.0",
    "pillow>=12.3.0",
    "psycopg>=3.3.5",
    "django-environ>=0.14.0",
    "python-slugify>=9.1.2",
    "redis>=5.0",
]

[dependency-groups]
dev = [
    "django-tailwind[reload]>=4.5.0",
    "django-debug-toolbar>=8.0.0",
    "django-extensions>=4.1",
    "ipython>=9.17.1",
    "pytest-django>=4.14.0",
    "pytest>=8.3.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.14.0",
    "mypy>=1.11.0,<1.14.0",
    "django-stubs>=5.1.1",
    "cookiecutter>=2.7.1",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.development"
python_files = ["test_*.py", "*_test.py"]
addopts = "--cov=. --cov-report=term-missing --cov-report=html"

[tool.ruff]
line-length = 119
target-version = "py314"
exclude = ["migrations", ".venv", "env", "staticfiles", "media"]

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP", "B", "C4"]

[tool.mypy]
python_version = "3.14"
check_untyped_defs = true
ignore_missing_imports = true
explicit_package_bases = true
exclude = ["migrations", ".venv", "env"]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings.development"
