upstream web_backend {
    server web:8000;
}

server {
    listen 80;
    server_name profiflow.loc; # Локально

    # Задел под SSL на проде:
    # listen 443 ssl;
    # ssl_certificate /etc/nginx/ssl/live/profiflow.ru/fullchain.pem;
    # ssl_certificate_key /etc/nginx/ssl/live/profiflow.ru/privkey.pem;

    location / {
        proxy_pass http://web_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # ЗАКОММЕНТИРОВАНО ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ!
    # Пусть Django (runserver) сам отдает статику на лету,
    # чтобы работал hot-reload Tailwind.
    # На проде раскомментировать!
    # location /static/ {
    #     alias /app/staticfiles/;
    # }

    location /media/ {
        alias /app/media/;
    }
}
