upstream web_backend {
    server web:8000;
}

# Блок для HTTP (Редирект на HTTPS и ловля ACME-проверок Certbot)
server {
    listen 80;
    server_name profiflow.pro www.profiflow.pro;

    # Специальный путь для проверки Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Редирект всего остального трафика на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Блок для HTTPS
server {
    listen 443 ssl;
    server_name profiflow.pro www.profiflow.pro;

    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/profiflow.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/profiflow.pro/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://web_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
