# Generated by Django 6.1.1 on 2026-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL (slug)')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название города')),
                ('region', models.CharField(blank=True, help_text='Например: Амурская область', max_length=150, null=True, verbose_name='Регион/Область')),
                ('timezone', models.CharField(default='Asia/Yakutsk', max_length=50, verbose_name='Часовой пояс')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'locations_city',
                'unique_together': {('name', 'region')},
            },
        ),
    ]
