# Generated by Django 6.1.1 on 2026-10-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='City')),
                ('booking_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('timezone', models.CharField(default='Asia/Yakutsk', max_length=50)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('is_onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Profile',
                'verbose_name_plural': 'Master Profiles',
                'db_table': 'users_master_profile',
            },
        ),
    ]
