# Generated by Django 6.1.1 on 2026-10-06 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_remove_user_avatar_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterprofile',
            options={'verbose_name': 'Профиль мастера', 'verbose_name_plural': 'Профили мастеров'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='booking_slug',
            field=models.SlugField(blank=True, help_text='Уникальная ссылка вида profiflow.pro/m/slug', max_length=100, null=True, unique=True, verbose_name='URL для записи (slug)'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='currency',
            field=models.CharField(default='RUB', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='is_onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Онбординг пройден'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='timezone',
            field=models.CharField(default='Asia/Yakutsk', max_length=50, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/clients/avatars/', verbose_name='Аватар')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Город')),
                ('favorites_masters', models.ManyToManyField(blank=True, related_name='favorited_by', to='users.masterprofile', verbose_name='Избранные мастера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
                'db_table': 'users_client_profile',
            },
        ),
    ]
