# Generated by Django 6.1.1 on 2026-10-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0003_alter_masterprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Город'),
        ),
    ]
