# Generated by Django 6.1.1 on 2026-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_masterprofile_first_name_masterprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес (улица, дом, кабинет)'),
        ),
    ]
