# Generated by Django 6.1.1 on 2026-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('catalog', '0003_alter_service_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='catalog.service', verbose_name='Услуга'),
        ),
    ]
