# Generated by Django 6.1.1 on 2026-10-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='services',
        ),
    ]
